### ISSUE TITLE
[Feature] Support remote sockets/server connection

### ISSUE THREAD

**Issue by mlehner616** [neurogeek/haproxyctl#4]
Currently there's no way to connect haproxyctl to a remote TCP socket.

Right now, I can use the following to connect directly to the socket but it'd be nice to have a utility to do this.
#### Socket Config

```
stats socket ipv4@0.0.0.0:80 level admin
```
#### Telnet Command

```
[root@localhost ~]# telnet 1.2.3.4 80
```
#### haproxyctl

```
[root@localhost ~]# haproxyctl -k 1.2.3.4:80
Traceback (most recent call last):
  File "/usr/local/bin/haproxyctl", line 109, in <module>
    sts = main(args)
  File "/usr/local/bin/haproxyctl", line 80, in main
    h_so = HaPConn(args.socket)
  File "/usr/local/lib/python2.6/site-packages/haproxy/conn.py", line 16, in __init__
    self.open()
  File "/usr/local/lib/python2.6/site-packages/haproxy/conn.py", line 24, in open
    self.sock.connect(self.sfile)
  File "<string>", line 1, in connect
socket.error: [Errno 2] No such file or directory
```

**Comment by No1zzz** [comment]
It will be nice.

**Comment by neurogeek** [comment]
@mlehner616 Thanks for filing this request.
I just made a release: v0.4 that should allow you to use TCP sockets.
Commit: https://github.com/neurogeek/haproxyctl/commit/a75ff230d7c2cad7cd8b57da7c015891683b8428

Please let me know if you find it useful.

Cheers,
